/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spellingbee;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author adamh
 */
public class GameFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());
    ArrayList<Word> words = new ArrayList<>();
    Word currentWord;
    
    int score = 0;
    int questionNumber = 0;
    
    
    /**
     * Creates new form mainInterface
     */
    public GameFrame() {
        initComponents();
        //modifying hintTextArea
        hintTextArea.setLineWrap(true);
        hintTextArea.setWrapStyleWord(true);
        hintTextArea.setEditable(false);
        hintTextArea.setOpaque(true);
        
        createWordList();
        startGame();
    }
    
    private void createWordList(){
        words.add(new Word(
                "imprisonment",
                "The state of being kept in prison as a punishment",
                ""
        ));
        
        words.add(new Word(
                "hypothesis",
                "A proposed explanation for a phenomenon made as a starting point for further investigation",
                ""
        ));
        
        words.add(new Word(
                "juxtaposition",
                "The fact of two things being seen or palced close together with contrasting effect",
                ""
        ));
        words.add(new Word(
                "acquiesce",
                "To accept, agree, or give in to someting reluctantly without protesting",
                ""));
        
        words.add(new Word(
                "participation",
                "The action of taking part in something",
                "Testing branch"
        ));
        
    }
    
    private void startGame(){
        score = 0;
        scoresLabel.setText(String.valueOf(score));
        nextWord();
    }
    
    private void nextWord(){
        Random random = new Random();
        
        currentWord = words.get(random.nextInt(words.size()));
        
        wordLabel.setText(currentWord.getSpelling());
        
        hintTextArea.setText(currentWord.getDefinition());
        
        answerField.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hint = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        answerText = new javax.swing.JLabel();
        wordLabel = new javax.swing.JLabel();
        scoresText = new javax.swing.JLabel();
        scoresLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hintTextArea = new javax.swing.JTextArea();
        spellText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        hint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hint.setText("Hint");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        answerText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        answerText.setText("Answer");

        wordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wordLabel.setForeground(new java.awt.Color(255, 51, 51));
        wordLabel.setText("Word");

        scoresText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoresText.setText("Scores");

        scoresLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoresLabel.setForeground(new java.awt.Color(0, 71, 255));
        scoresLabel.setText("-");

        hintTextArea.setEditable(false);
        hintTextArea.setColumns(20);
        hintTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hintTextArea.setForeground(new java.awt.Color(51, 51, 255));
        hintTextArea.setRows(5);
        jScrollPane1.setViewportView(hintTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(wordLabel)
                        .addGap(325, 325, 325))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hint)
                    .addComponent(answerText)
                    .addComponent(scoresText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoresLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(wordLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(hint))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerText))
                .addGap(35, 35, 35)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoresText)
                    .addComponent(scoresLabel))
                .addGap(79, 79, 79))
        );

        spellText.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        spellText.setText("Spell");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(spellText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(spellText)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String answer = answerField.getText();
        
        if(answer.equalsIgnoreCase(currentWord.getSpelling())){
            score++;
            JOptionPane.showMessageDialog(this, "Correct!");
        }
        else {
            JOptionPane.showMessageDialog(this, "Wrong!\nCorrect Answer: " + currentWord.getSpelling());
        }
        scoresLabel.setText(String.valueOf(score));
        nextWord();
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerText;
    private javax.swing.JLabel hint;
    private javax.swing.JTextArea hintTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel scoresLabel;
    private javax.swing.JLabel scoresText;
    private javax.swing.JLabel spellText;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
