/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package spellingbee;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author adamh
 */
public class GameFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameFrame.class.getName());
    ArrayList<Word> words = new ArrayList<>();
    Word currentWord;
    private GameSettings settings;
    
    int score = 0;
    int questionsCount = 0;
    private GameTimer gameTimer;
    
    
    /**
     * Creates new form mainInterface
     */
    public GameFrame(GameSettings settings) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        //modifying hintTextArea
        hintTextArea.setLineWrap(true);
        hintTextArea.setWrapStyleWord(true);
        hintTextArea.setEditable(false);
        hintTextArea.setOpaque(true);
        answerField.setEnabled(false);
        submitButton.setEnabled(false);
        
        this.settings = settings;
        
        soundEffectLabel.setText("Sound Enabled: " + settings.isSoundEnabled());
        endlessModeLabel.setText("Endless Mode Enabled: " + settings.isEndlessModeEnabled());
        timerLabel.setText("Timer Enabled: " + settings.isTimerEnabled());
        showHintLabel.setText("Show Hint Enabled: " + settings.isShowHintEnabled());
        difficultyLabel.setText("Difficulty: " + settings.getDifficulty());
        volumeLabel.setText("Volume: " + settings.getVolume());
        
        words = WorldLoader.loadWords("words.txt");
        gameTimer = new GameTimer(10,
        () -> timerProgress.setValue(gameTimer.getTimeLeft()),
        () -> evaluateAnswer());
    }

    
    private void startGame(){
        score = 0;
        scoresLabel.setText(String.valueOf(score));
        answerField.setEnabled(true);
        submitButton.setEnabled(true);
                
        loadNextQuestion();
    }
    
    private void loadNextQuestion(){
        
        if(!settings.isEndlessModeEnabled() && questionsCount >= settings.getQuestions()){
            gameOver();
            return;
        }
        
        questionsCount++;
        nextWord();
        playCurrentQuestion();
        timerProgress.setValue(timerProgress.getMaximum());
        gameTimer.restart();
    }
    
    private void nextWord(){
        Random random = new Random();
        
        currentWord = words.get(random.nextInt(words.size()));
        
        wordLabel.setText("");
        
        hintTextArea.setText(currentWord.getDefinition());
        
        answerField.setText("");
    }
    
    private void playCurrentQuestion(){
        AudioPlayer.playAudio("audio/canyouspell.wav", settings);
        AudioPlayer.playAudio(currentWord.getAudioPath(), settings);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hint = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        answerText = new javax.swing.JLabel();
        wordLabel = new javax.swing.JLabel();
        scoresText = new javax.swing.JLabel();
        scoresLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hintTextArea = new javax.swing.JTextArea();
        timerText = new javax.swing.JLabel();
        timerProgress = new javax.swing.JProgressBar();
        soundEffectLabel = new javax.swing.JLabel();
        showHintLabel = new javax.swing.JLabel();
        endlessModeLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        volumeLabel = new javax.swing.JLabel();
        spellText = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        hint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hint.setText("Hint");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        answerText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        answerText.setText("Answer");

        wordLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        wordLabel.setForeground(new java.awt.Color(255, 51, 51));
        wordLabel.setText("-");

        scoresText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoresText.setText("Scores");

        scoresLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scoresLabel.setForeground(new java.awt.Color(0, 71, 255));
        scoresLabel.setText("-");

        hintTextArea.setEditable(false);
        hintTextArea.setColumns(20);
        hintTextArea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hintTextArea.setForeground(new java.awt.Color(51, 51, 255));
        hintTextArea.setRows(5);
        jScrollPane1.setViewportView(hintTextArea);

        timerText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timerText.setForeground(new java.awt.Color(255, 0, 102));
        timerText.setText("Timer");

        timerProgress.setMaximum(10);

        soundEffectLabel.setText("jLabel1");

        showHintLabel.setText("jLabel2");

        endlessModeLabel.setText("jLabel3");

        timerLabel.setText("jLabel4");

        difficultyLabel.setText("jLabel1");

        volumeLabel.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(soundEffectLabel)
                            .addComponent(showHintLabel)
                            .addComponent(endlessModeLabel)
                            .addComponent(timerLabel)
                            .addComponent(difficultyLabel)
                            .addComponent(volumeLabel))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(wordLabel)
                        .addGap(325, 325, 325))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hint)
                    .addComponent(answerText)
                    .addComponent(scoresText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(scoresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(timerText)
                        .addGap(18, 18, 18)
                        .addComponent(timerProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(wordLabel)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(hint))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answerText))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(scoresText)
                                .addComponent(scoresLabel)
                                .addComponent(timerText))
                            .addComponent(timerProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(soundEffectLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showHintLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(endlessModeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(difficultyLabel)
                        .addGap(18, 18, 18)
                        .addComponent(volumeLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        spellText.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        spellText.setText("Spell");

        startButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(0, 91, 78));
        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(spellText)
                .addGap(35, 35, 35)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spellText)
                    .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void evaluateAnswer(){
        gameTimer.stop();
                String answer = answerField.getText();
        
        if(answer.equalsIgnoreCase(currentWord.getSpelling())){
            scoresLabel.setText(String.valueOf(++score));
            AudioPlayer.playSound("sound/correct.wav", settings);
            JOptionPane.showMessageDialog(this, "Correct!");
        }
        else {
            AudioPlayer.playSound("sound/incorrect.wav", settings);
            JOptionPane.showMessageDialog(this, "Correct Answer: " + currentWord.getSpelling(), "Wrong Answer!", JOptionPane.ERROR_MESSAGE);
            gameOver();
            return;
        }
        loadNextQuestion();
    }
    
    private void gameOver(){
        gameTimer.stop();
        timerProgress.setValue(timerProgress.getMinimum());
        
        JOptionPane.showMessageDialog(
        this, "Game Over!\nYour scores: " + score,
               "Game Over",
               JOptionPane.INFORMATION_MESSAGE
        );
        
        score = 0; scoresLabel.setText(String.valueOf(score));
        
        hintTextArea.setText("");
        answerField.setText("");
        
        answerField.setEnabled(false);
        submitButton.setEnabled(false);
        startButton.setEnabled(true);
    }
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        evaluateAnswer();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        startGame();
        startButton.setEnabled(false);
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainMenuFrame main = new MainMenuFrame(settings);
        main.setVisible(true);
        gameTimer.stop();
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameFrame(new GameSettings()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel answerText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JLabel endlessModeLabel;
    private javax.swing.JLabel hint;
    private javax.swing.JTextArea hintTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel scoresLabel;
    private javax.swing.JLabel scoresText;
    private javax.swing.JLabel showHintLabel;
    private javax.swing.JLabel soundEffectLabel;
    private javax.swing.JLabel spellText;
    private javax.swing.JButton startButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JProgressBar timerProgress;
    private javax.swing.JLabel timerText;
    private javax.swing.JLabel volumeLabel;
    private javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
