/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package spellingbee;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author adamh
 */
public class SettingsDialog extends javax.swing.JDialog {
   private GameSettings settings;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SettingsDialog.class.getName());
    /**
     * Creates new form SettingsDialog
     */
    public SettingsDialog(java.awt.Frame parent,boolean modal, GameSettings settings) {
        super(parent, modal);
        initComponents();
        this.settings = settings;
        
        
        SpinnerNumberModel model = new SpinnerNumberModel(settings.getQuestions(), 5, 100, 5);
        questionSpinner.setModel(model);
        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) questionSpinner.getEditor();
        editor.getTextField().setEditable(false);
        
        setResizable(false);
        setLocationRelativeTo(parent);
        loadSettings();
    } 
    
    private void loadSettings(){
        soundEffectToggleButton.setSelected(settings.isSoundEnabled());
        endlessModeToggleButton.setSelected(settings.isEndlessModeEnabled());
        timerToggleButton.setSelected(settings.isTimerEnabled());
        showHintToggleButton.setSelected(settings.isShowHintEnabled());
        
        themeComboBox.setSelectedItem(settings.getTheme());
        volumeSlider.setValue(settings.getVolume());
        questionSpinner.setEnabled(!settings.isEndlessModeEnabled());
    }
    
    private void saveSettings(){
        settings.setSoundEnabled(soundEffectToggleButton.isSelected());
        settings.setEndlessModeEnabled(endlessModeToggleButton.isSelected());
        settings.setTimerEnabled(timerToggleButton.isSelected());
        settings.setShowHintEnabled(showHintToggleButton.isSelected());
        
        settings.setTheme(themeComboBox.getSelectedItem().toString());
        settings.setVolume(volumeSlider.getValue());
        settings.setQuestions(Integer.parseInt(questionSpinner.getValue().toString()));
    }
    
    private void updateControls(){
      questionSpinner.setEnabled(!endlessModeToggleButton.isSelected());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        soundEffectText = new javax.swing.JLabel();
        volumeText = new javax.swing.JLabel();
        endlessModeText = new javax.swing.JLabel();
        timerText = new javax.swing.JLabel();
        showHintText = new javax.swing.JLabel();
        themeText = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        themeComboBox = new javax.swing.JComboBox<>();
        soundEffectToggleButton = new javax.swing.JToggleButton();
        volumeSlider = new javax.swing.JSlider();
        timerToggleButton = new javax.swing.JToggleButton();
        showHintToggleButton = new javax.swing.JToggleButton();
        endlessModeToggleButton = new javax.swing.JToggleButton();
        resetButton = new javax.swing.JButton();
        questionSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel8.setText("jLabel8");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        soundEffectText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soundEffectText.setText("Sound Effect");

        volumeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        volumeText.setText("Volume");

        endlessModeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        endlessModeText.setText("Endless Mode");

        timerText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timerText.setText("Timer");

        showHintText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showHintText.setText("Show Hint");

        themeText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themeText.setText("Theme");

        saveButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        themeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light", "Dark" }));

        soundEffectToggleButton.setText("On");

        timerToggleButton.setText("On");

        showHintToggleButton.setText("On");

        endlessModeToggleButton.setText("On");
        endlessModeToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endlessModeToggleButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        questionSpinner.setName(""); // NOI18N
        questionSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                questionSpinnerStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(volumeText)
                                        .addGap(64, 64, 64)
                                        .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(endlessModeText)
                                            .addComponent(timerText)
                                            .addComponent(showHintText))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(timerToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(showHintToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                            .addComponent(endlessModeToggleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(27, 27, 27)
                                        .addComponent(questionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(soundEffectText)
                        .addGap(32, 32, 32)
                        .addComponent(soundEffectToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(themeText)
                        .addGap(18, 18, 18)
                        .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soundEffectText)
                    .addComponent(themeText)
                    .addComponent(themeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soundEffectToggleButton))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(volumeText)
                            .addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(endlessModeText)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(endlessModeToggleButton)
                                .addComponent(questionSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timerText)
                            .addComponent(timerToggleButton))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showHintText)
                            .addComponent(showHintToggleButton))
                        .addGap(55, 55, 55)
                        .addComponent(saveButton))
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Settings");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        saveSettings();
        JOptionPane.showMessageDialog(this, "Settings have been saved.");
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        settings.resetToDefault();
        loadSettings();
        JOptionPane.showMessageDialog(this, "Settings have been reset to default.");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void questionSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_questionSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_questionSpinnerStateChanged

    private void endlessModeToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endlessModeToggleButtonActionPerformed
        // TODO add your handling code here:
        updateControls();
    }//GEN-LAST:event_endlessModeToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SettingsDialog dialog = new SettingsDialog(new javax.swing.JFrame(), true, new GameSettings());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endlessModeText;
    private javax.swing.JToggleButton endlessModeToggleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner questionSpinner;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel showHintText;
    private javax.swing.JToggleButton showHintToggleButton;
    private javax.swing.JLabel soundEffectText;
    private javax.swing.JToggleButton soundEffectToggleButton;
    private javax.swing.JComboBox<String> themeComboBox;
    private javax.swing.JLabel themeText;
    private javax.swing.JLabel timerText;
    private javax.swing.JToggleButton timerToggleButton;
    private javax.swing.JSlider volumeSlider;
    private javax.swing.JLabel volumeText;
    // End of variables declaration//GEN-END:variables
}
